### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by dankim444** [Jasefig/Nets2130-Project#6]
- [ ] Add "loading..." message when image generation is happening
- [ ] fix vote mechanism bug (Dan)
- [ ] Update total_votes in Day table whenever a new vote is added, update total_participants in Day table when a user participates in voting
- [ ] Add a "thank you for participating" page
- [ ] Make UI look cleaner

**Comment by dankim444** [comment]
Need to do aggregation on UserDailyActivity table:
CREATE TABLE UserDailyActivity (
    user_id VARCHAR(255),
    date DATE,
    flags_made INT DEFAULT 0,
    votes_made INT DEFAULT 0,
    images_submitted INT DEFAULT 0,
    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, date),
    FOREIGN KEY (user_id) REFERENCES User(user_id)
);
